public with sharing class OrderService {

    // Méthode pour valider les commandes
    public static void validateOrder(Order orderToValidate) {
        // TODO: Implémenter la logique de validation de la commande
    }

    //TODO : Completer la classe avec toute autre méthode nécessaire pour gérer la logique métier liée aux commandes


    /* On récupère le compte associé à la commande puis on récupère tous les oderItem associé a la commande.
    Après , on fait une vérification en fonction du type de compte associé (professionnel ou particulier)
    et on implémente la logique métier avec 'if' et le nombre de produits associés à la commande. (3 ou 5)
        */
        
}